### ISSUE TITLE
BMCP chess program by Benjamin Rousseaux - WinBoard/UCI-protocol

### ISSUE THREAD

**Issue by yellow-panther** [maksimKorzh/bmcp#1]
Hello maksimKorzh,

> cf. https://blog.rosseaux.net/ section "Games" https://www.rosseaux.com/downloads/bmcp.zip 

do you have plans for an implementation of the UCI-protocol http://download.shredderchess.com/div/uci.zip or WinBoard-protocol a.k.a. CECP http://home.hccnet.nl/h.g.muller/engine-intf.html - http://hgm.nubati.net/CECP.html into BMCP and a JavaScript (js-file > commandline parameter) to download?

e.g. Lozza JS https://github.com/op12no2/lozza  or Rapchess https://github.com/Thibor/Chess-Engine-Rapchess

Regards,

**Comment by maksimKorzh** [comment]
Hello, @yellow-panther, well, basically I'm not going to implement UCI/Winboard protocols because bmcp is not intended to play with other engines - it's too week. It's intended to be the source of inspirations for beginner chess programmers. I wish I had such sort of resource when I started chess programming for about three years ago.

Check up my https://github.com/maksimKorzh/Chenglite engine that has UCI protocol and can play against other programs.

Hope this answers your question)
Take care!
