### ISSUE TITLE
Project name conflict with my BMCP chess program project from 2012

### ISSUE THREAD

**Issue by BeRo1985** [maksimKorzh/bmcp#2]
See https://blog.rosseaux.net/ under section "Games"  and https://github.com/maksimKorzh/bmcp/issues/1 . So please rename your project, but of course only if it is possible and if you don't have any objections to it, thanks. At least "my" BMCP chess program project seems to be some years older. ;-)

**Comment by maksimKorzh** [comment]
@BeRo1985 I deeply respect the fact you've found the name "bmcp" and I'd love to change it's name, but the point is that this code is written specially for my youtube tutorial series on how to write a really minimalist chess program. Changing name here would lead to the need of changing it in the entire tutorial.

I'm just wondering if you could forgive me sharing this name, especially bearing in mind the fact that I don't claim this program to be the production software - it's just an illustration of how one can proceed from scratch in order to get a working chess program even if he is a beginner in programming.

So can I please leave the name as is?
